development:
  api_url: http://example.com/api/json
  username: user
  password: pass
  
production:
  api_url: http://example.com/api/json
  username: user
  password: pass

config:
  change_default_hook_position: false
